#!/bin/bash
# download docker on linux 
apt-get update
apt-get install -y docker docker.io
systemctl enable docker
systemctl start docker

# install git
apt-get install -y git
mkdir /home/JLink && cd /home/JLink

git clone https://github.com/ObraztsovOleg/im_ok_firmware.git
docker pull fjmolinas/jlink
